### ISSUE TITLE
attributes.json field for flavour?

### ISSUE THREAD

**Issue by skalarproduktraum** [saalfeldlab/n5#17] opened 2017-12-07 09:41 UTC
(Also from the hackathon discussion with @tpietzsch, @ctrueden and @hanslovsky)

We were discussing whether it'd make sense to have a field in the attributes.json that specifies what flavour this n5 dataset contains, to circumvent the problem of "The file says it's HDF5 but I can't open it!1!!".

Opinions?

**Comment by axtimwalde** [comment] 2017-12-07 17:35
Is "flavour" the British spelling of "version"? If yes, this issue is a duplicate of https://github.com/saalfeldlab/n5/issues/15

**Comment by skalarproduktraum** [comment] 2017-12-08 20:45
No, this was not intended as version, which is why I actually opened a separate issue. 

The point I was trying to make is that N5 can contain anything, so it'd be nice if the attributes.json were required to contain a name, or tag, or sth that describes what actually is inside. Similar to FourCC (https://en.wikipedia.org/wiki/FourCC) in AVI files.

What's your opinion on that?

**Comment by axtimwalde** [comment] 2018-01-26 02:59
Everybody who uses N5 for something particular that they want to tag with a flavour attribute or similar can do so.  In these cases, it is the responsibility of the user to test for this tag if desired which is covered by general purpose attributes.

**Closed by axtimwalde** 2018-01-26 02:59 UTC
